In [6]:
import numpy as np

In [7]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.linspace(0, 10, 41)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,
        4.5 ,  4.75,  5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,
        6.75,  7.  ,  7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,
        9.  ,  9.25,  9.5 ,  9.75, 10.  ])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.random.rand()

0.9760878071304201

In [12]:
np.random.randn()   # Standard normal distribution

0.9377346624749224

In [13]:
np.random.randint(0,2, (2,5)) # Random integer

array([[1, 0, 1, 0, 0],
       [1, 1, 1, 0, 1]])

In [14]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [15]:
arr = np.arange(0,25)

In [16]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
ranarr = np.random.randint(0, 101, 10)

In [18]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [19]:
ranarr.max()

np.int64(99)

In [20]:
ranarr.min()

np.int64(2)

In [21]:
ranarr.argmax() # Returns index where the maximum value is.

np.int64(5)

In [22]:
arr = np.arange(0, 11)

In [23]:
arr[8]

np.int64(8)

In [24]:
arr[0:5] # Slicing

array([0, 1, 2, 3, 4])

In [25]:
arr[:5] # From beginning to index 5

array([0, 1, 2, 3, 4])

In [26]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[0:5] = 100 #Slicing and broadcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [28]:
arr = np.arange(0,11)
print(arr)
slice_of_arr = arr[0:5]
print(slice_of_arr)
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr) # Notice how the original array has also changed. This is because slice_of_arr is a view of arr, not a copy.

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[99 99 99 99 99]
[99 99 99 99 99  5  6  7  8  9 10]


In [ ]:
arr = np.arange(0,11)
print(arr)
arr_copy = arr.copy() # Now arr_copy is a copy of arr, not a view.
slice_of_arr = arr_copy[0:5]
print(slice_of_arr)
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[99 99 99 99 99]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [38]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d.shape

(3, 3)

In [35]:
arr_2d[0][2]

np.int64(15)

In [37]:
arr_2d[:2,1:] # Slicing 2D array

array([[10, 15],
       [25, 30]])

In [39]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
arr[arr > 4] # Returns values greater than 4

array([ 5,  6,  7,  8,  9, 10])